In [71]:
import numpy as np
import pandas as pd 

In [180]:
class MyLR:
    def __init__(self):
        """Initialize slope and intercept as None"""
        self.m = None
        self.b = None

    def fit(self, X_train, y_train):
        """
        Fit the model using the training data.
        
        Args:
        X_train (np.ndarray): 1D array of features.
        y_train (np.ndarray): 1D array of target values.
        """
        # Using vectorized NumPy operations for efficiency
        X_mean = np.mean(X_train)
        y_mean = np.mean(y_train)
        
        num = np.sum((X_train - X_mean) * (y_train - y_mean))
        deno = np.sum((X_train - X_mean) ** 2)
        
        self.m = num / deno
        self.b = y_mean - (self.m * X_mean)

    def predict(self, X_test):
        """
        Predict the target values using the learned model.
        
        Args:
        X_test (np.ndarray or float): Input feature(s) to predict.
        
        Returns:
        np.ndarray or float: Predicted target values.
        """
        if self.m is None or self.b is None:
            raise ValueError("Model has not been fitted yet. Please call 'fit' first.")
        return self.m * X_test + self.b

    
    def predict(self,X_test,y_test):
        if self.m is None or self.b is None:
            raise ValueError("Model has not been fitted yet. Please call 'fit' first.")
        
        # Handle scalar inputs (single value) and arrays separately
        if np.isscalar(X_test):
            predictions = self.m * X_test + self.b
            if y_test is not None:
                print(f"CGPA of student: {X_test:.2f}, Original Package: {y_test:.2f}, Predicted Package: {predictions:.2f}")
            return predictions
        else:
            predictions = self.m * X_test + self.b
            if y_test is not None:
                for i in range(len(X_test)):
                    print(f"CGPA of student: {X_test[i]:.2f}, Original Package: {y_test[i]:.2f}, Predicted Package: {predictions[i]:.2f}")
            return predictions

In [164]:
df = pd.read_csv("placement (1).csv")

In [74]:
df


cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [75]:
x= df.iloc[:,0].values
# Values because we want to extract a numpy array
x

array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
       6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94, 7.48, 7.28, 6.85,
       6.14, 6.19, 6.53, 7.28, 8.31, 5.42, 5.94, 7.15, 7.36, 8.1 , 6.96,
       6.35, 7.34, 6.87, 5.99, 5.9 , 8.62, 7.43, 9.38, 6.89, 5.95, 7.66,
       5.09, 7.87, 6.07, 5.84, 8.63, 8.87, 9.58, 9.26, 8.37, 6.47, 6.86,
       8.2 , 5.84, 6.6 , 6.92, 7.56, 5.61, 5.48, 6.34, 9.16, 7.36, 7.6 ,
       5.11, 6.51, 7.56, 7.3 , 5.79, 7.47, 7.78, 8.44, 6.85, 6.97, 6.94,
       8.99, 6.59, 7.18, 7.63, 6.1 , 5.58, 8.44, 4.26, 4.79, 7.61, 8.09,
       4.73, 6.42, 7.11, 6.22, 7.9 , 6.79, 5.83, 6.63, 7.11, 5.98, 7.69,
       6.61, 7.95, 6.71, 5.13, 7.05, 7.62, 6.66, 6.13, 6.33, 7.76, 7.77,
       8.18, 5.42, 8.58, 6.94, 5.84, 8.35, 9.04, 7.12, 7.4 , 7.39, 5.23,
       6.5 , 5.12, 5.1 , 6.06, 7.33, 5.91, 6.78, 7.93, 7.29, 6.68, 6.37,
       5.84, 6.05, 7.2 , 6.1 , 5.64, 7.14, 7.91, 7.19, 7.91, 6.76, 6.93,
       4.85, 6.17, 5.84, 6.07, 5.66, 7.57, 8.28, 6.

In [76]:
y = df.iloc[:,1].values

In [77]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [78]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [79]:
X_train

array([7.14, 8.93, 5.42, 5.1 , 7.77, 6.76, 6.89, 6.68, 7.91, 7.89, 8.71,
       7.95, 6.61, 6.26, 6.53, 6.42, 5.11, 6.09, 6.93, 7.04, 5.94, 6.05,
       5.83, 5.95, 9.31, 5.58, 7.88, 6.13, 7.76, 4.85, 6.19, 8.6 , 6.07,
       7.18, 5.12, 7.39, 8.25, 8.28, 7.13, 7.35, 5.66, 5.99, 8.01, 7.14,
       6.34, 6.89, 5.42, 6.47, 7.69, 7.4 , 7.28, 5.95, 7.38, 6.93, 8.99,
       7.36, 7.08, 5.38, 7.56, 8.22, 5.84, 6.78, 7.19, 7.28, 6.79, 6.12,
       6.85, 8.2 , 6.84, 7.37, 6.22, 6.61, 5.23, 7.21, 6.85, 6.19, 7.3 ,
       6.17, 5.89, 8.09, 7.11, 4.26, 6.94, 5.98, 6.71, 7.33, 9.06, 6.1 ,
       5.48, 6.1 , 7.56, 7.29, 5.84, 7.48, 7.61, 5.79, 5.61, 7.34, 9.38,
       7.91, 6.94, 7.94, 8.31, 6.96, 6.93, 7.11, 8.44, 8.18, 6.66, 8.44,
       7.12, 6.3 , 5.84, 6.98, 7.63, 5.64, 7.43, 8.87, 7.84, 5.84, 9.58,
       8.37, 7.63, 6.31, 6.5 , 8.11, 6.07, 4.73, 7.3 , 6.51, 7.28, 6.92,
       6.35, 8.62, 7.05, 9.26, 6.33, 6.22, 6.94, 5.13, 8.13, 5.9 , 9.04,
       6.06, 7.57, 8.1 , 9.16, 5.84, 7.89, 6.63, 7.

In [80]:
X_train.shape[0]


160

In [81]:
X_train.shape

(160,)

In [82]:
X_train.mean()

6.989937500000001

In [182]:
lr = MyLR()

In [184]:
lr.fit(X_train,y_train)

In [186]:
X_test[0]

8.58

In [188]:
lr.predict(X_test[0],y_test[0])

CGPA of student: 8.58, Original Package: 4.10, Predicted Package: 3.89


3.891116009744203

In [190]:
y_test[0]

4.1

In [192]:
X_test

array([8.58, 7.15, 5.88, 6.22, 4.57, 4.79, 5.32, 6.86, 8.35, 6.87, 8.94,
       7.9 , 6.93, 5.91, 7.32, 7.82, 5.09, 7.42, 6.94, 7.73, 6.19, 7.28,
       6.73, 7.2 , 8.21, 6.75, 7.87, 7.6 , 8.63, 5.12, 8.15, 7.36, 8.31,
       6.6 , 6.59, 7.47, 7.93, 6.29, 6.37, 6.47])

In [194]:
y_test

array([4.1 , 3.49, 2.08, 2.33, 1.94, 1.48, 1.86, 3.09, 4.21, 2.87, 3.65,
       4.  , 2.89, 2.6 , 2.99, 3.25, 1.86, 3.67, 2.37, 3.42, 2.48, 3.65,
       2.6 , 2.83, 4.08, 2.56, 3.58, 3.81, 4.09, 2.01, 3.63, 2.92, 3.51,
       1.94, 2.21, 3.34, 3.34, 3.23, 2.01, 2.61])

In [176]:
lr.predict(X_test,y_test)

CGPA of student: 8.58, Original Package: 4.10, Predicted Package: 3.89
CGPA of student: 7.15, Original Package: 3.49, Predicted Package: 3.09
CGPA of student: 5.88, Original Package: 2.08, Predicted Package: 2.38
CGPA of student: 6.22, Original Package: 2.33, Predicted Package: 2.57
CGPA of student: 4.57, Original Package: 1.94, Predicted Package: 1.65
CGPA of student: 4.79, Original Package: 1.48, Predicted Package: 1.78
CGPA of student: 5.32, Original Package: 1.86, Predicted Package: 2.07
CGPA of student: 6.86, Original Package: 3.09, Predicted Package: 2.93
CGPA of student: 8.35, Original Package: 4.21, Predicted Package: 3.76
CGPA of student: 6.87, Original Package: 2.87, Predicted Package: 2.94
CGPA of student: 8.94, Original Package: 3.65, Predicted Package: 4.09
CGPA of student: 7.90, Original Package: 4.00, Predicted Package: 3.51
CGPA of student: 6.93, Original Package: 2.89, Predicted Package: 2.97
CGPA of student: 5.91, Original Package: 2.60, Predicted Package: 2.40
CGPA o

array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])